name: publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Authenticate on AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      - name: Import signing key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Install go
        id: setup_go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.17'
      - name: Test
        run: >
          make test
      - name: Publish
        run: >
          make publish GPG_KEY=${{ secrets.GPG_ID }} BUCKET=${{ secrets.AWS_BUCKET }}
