name: publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Authenticate on AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      - name: Import signing key
        run: >
          apt update && \
          apt insatll -y gpg && \
          echo ${{ secrets.GPG_KEY }} | gpg --import 
      - name: Publish
        run: >
          make publish GPG_KEY=acwrenn BUCKET=${{ secrets.AWS_BUCKET }}
